// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AddArc
SEXP AddArc(SEXP net_ptr, SEXP parent_node_name, SEXP child_node_name);
RcppExport SEXP sip_AddArc(SEXP net_ptrSEXP, SEXP parent_node_nameSEXP, SEXP child_node_nameSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP net_ptr = Rcpp::as<SEXP >(net_ptrSEXP);
        SEXP parent_node_name = Rcpp::as<SEXP >(parent_node_nameSEXP);
        SEXP child_node_name = Rcpp::as<SEXP >(child_node_nameSEXP);
        SEXP __result = AddArc(net_ptr, parent_node_name, child_node_name);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// AddNode
SEXP AddNode(SEXP net_ptr, SEXP node_name, SEXP node_type, SEXP node_states);
RcppExport SEXP sip_AddNode(SEXP net_ptrSEXP, SEXP node_nameSEXP, SEXP node_typeSEXP, SEXP node_statesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP net_ptr = Rcpp::as<SEXP >(net_ptrSEXP);
        SEXP node_name = Rcpp::as<SEXP >(node_nameSEXP);
        SEXP node_type = Rcpp::as<SEXP >(node_typeSEXP);
        SEXP node_states = Rcpp::as<SEXP >(node_statesSEXP);
        SEXP __result = AddNode(net_ptr, node_name, node_type, node_states);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// CreateNetwork_testing_func
int CreateNetwork_testing_func();
RcppExport SEXP sip_CreateNetwork_testing_func() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        int __result = CreateNetwork_testing_func();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// CreateSmlieNetwork
SEXP CreateSmlieNetwork();
RcppExport SEXP sip_CreateSmlieNetwork() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP __result = CreateSmlieNetwork();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// PopulateNode
void PopulateNode(SEXP net_ptr, SEXP node_name);
RcppExport SEXP sip_PopulateNode(SEXP net_ptrSEXP, SEXP node_nameSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        SEXP net_ptr = Rcpp::as<SEXP >(net_ptrSEXP);
        SEXP node_name = Rcpp::as<SEXP >(node_nameSEXP);
        PopulateNode(net_ptr, node_name);
    }
    return R_NilValue;
END_RCPP
}
// WriteNetwork
void WriteNetwork(SEXP net_ptr, SEXP filepath);
RcppExport SEXP sip_WriteNetwork(SEXP net_ptrSEXP, SEXP filepathSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        SEXP net_ptr = Rcpp::as<SEXP >(net_ptrSEXP);
        SEXP filepath = Rcpp::as<SEXP >(filepathSEXP);
        WriteNetwork(net_ptr, filepath);
    }
    return R_NilValue;
END_RCPP
}
