// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AddNode
SEXP AddNode(SEXP net_ptr, SEXP node_name, SEXP node_type, SEXP node_states);
RcppExport SEXP sip_AddNode(SEXP net_ptrSEXP, SEXP node_nameSEXP, SEXP node_typeSEXP, SEXP node_statesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP net_ptr = Rcpp::as<SEXP >(net_ptrSEXP);
        SEXP node_name = Rcpp::as<SEXP >(node_nameSEXP);
        SEXP node_type = Rcpp::as<SEXP >(node_typeSEXP);
        SEXP node_states = Rcpp::as<SEXP >(node_statesSEXP);
        SEXP __result = AddNode(net_ptr, node_name, node_type, node_states);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// CreateSmlieNetwork
SEXP CreateSmlieNetwork();
RcppExport SEXP sip_CreateSmlieNetwork() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP __result = CreateSmlieNetwork();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
