# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AddArc <- function(net_ptr, parent_node_name, child_node_name) {
    .Call('sip_AddArc', PACKAGE = 'sip', net_ptr, parent_node_name, child_node_name)
}

AddNode <- function(net_ptr, node_name, node_type, node_states) {
    .Call('sip_AddNode', PACKAGE = 'sip', net_ptr, node_name, node_type, node_states)
}

CreateNetwork_testing_func <- function() {
    .Call('sip_CreateNetwork_testing_func', PACKAGE = 'sip')
}

CreateSmlieNetwork <- function() {
    .Call('sip_CreateSmlieNetwork', PACKAGE = 'sip')
}

WriteNetwork <- function(net_ptr, filepath) {
    invisible(.Call('sip_WriteNetwork', PACKAGE = 'sip', net_ptr, filepath))
}

