# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AddArc <- function(net_ptr, parent_node_name, child_node_name) {
    .Call('sip_AddArc', PACKAGE = 'sip', net_ptr, parent_node_name, child_node_name)
}

AddNode <- function(net_ptr, node_name, node_type, node_states) {
    .Call('sip_AddNode', PACKAGE = 'sip', net_ptr, node_name, node_type, node_states)
}

CreateNetwork_testing_func <- function() {
    .Call('sip_CreateNetwork_testing_func', PACKAGE = 'sip')
}

CreateSmlieNetwork <- function() {
    .Call('sip_CreateSmlieNetwork', PACKAGE = 'sip')
}

DeleteArc <- function(net_ptr, parent_node_name, child_node_name) {
    invisible(.Call('sip_DeleteArc', PACKAGE = 'sip', net_ptr, parent_node_name, child_node_name))
}

DeleteNode <- function(net_ptr, node_name) {
    invisible(.Call('sip_DeleteNode', PACKAGE = 'sip', net_ptr, node_name))
}

ErrorCode2String <- function(error_code_) {
    .Call('sip_ErrorCode2String', PACKAGE = 'sip', error_code_)
}

GetLevelsAssociatedWithChanceOrDecisionNode <- function(net_ptr, node_name) {
    .Call('sip_GetLevelsAssociatedWithChanceOrDecisionNode', PACKAGE = 'sip', net_ptr, node_name)
}

GetLevelsAssociatedWithUtilityNode <- function(net_ptr, node_name) {
    .Call('sip_GetLevelsAssociatedWithUtilityNode', PACKAGE = 'sip', net_ptr, node_name)
}

GetNodeTable <- function(net_ptr, node_name) {
    .Call('sip_GetNodeTable', PACKAGE = 'sip', net_ptr, node_name)
}

SetNodeTable <- function(net_ptr, node_name, node_values) {
    invisible(.Call('sip_SetNodeTable', PACKAGE = 'sip', net_ptr, node_name, node_values))
}

NodeType <- function(net_ptr, node_name) {
    .Call('sip_NodeType', PACKAGE = 'sip', net_ptr, node_name)
}

NodeExistsQ <- function(net_ptr, node_name) {
    .Call('sip_NodeExistsQ', PACKAGE = 'sip', net_ptr, node_name)
}

WriteNetwork <- function(net_ptr, filepath) {
    invisible(.Call('sip_WriteNetwork', PACKAGE = 'sip', net_ptr, filepath))
}

